version: "3.8"

services:
  quiver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiver-db
    ports:
      - "8080:8080"
    volumes:
      - quiver-data:/app/data
    environment:
      # Server configuration
      - QUIVER_SERVER_PORT=8080
      - QUIVER_SERVER_HOST=0.0.0.0
      - QUIVER_LOG_LEVEL=info

      # Storage configuration
      - QUIVER_SERVER_STORAGE=/app/data
      - QUIVER_ENABLE_PERSISTENCE=true
      - QUIVER_PERSISTENCE_FORMAT=parquet
      - QUIVER_FLUSH_INTERVAL=300

      # Index configuration
      - QUIVER_INDEX_DIMENSION=768
      - QUIVER_INDEX_DISTANCE=cosine
      - QUIVER_ENABLE_HYBRID=true
      - QUIVER_MAX_CONNECTIONS=16
      - QUIVER_EF_CONSTRUCTION=200
      - QUIVER_EF_SEARCH=100

      # Performance configuration
      - QUIVER_ENABLE_METRICS=true
      - QUIVER_BATCH_SIZE=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  quiver-data:
    driver: local
