apiVersion: v1
kind: ConfigMap
metadata:
  name: quiver-config
data:
  quiver.yaml: |
    dimension: 1536
    distance: "cosine"
    max_elements: 1000000
    hnsw:
      m: 16
      ef_construction: 200
      ef_search: 100
    batch_size: 100
    persistence:
      interval: "5m"
      path: "/data/quiver"
    backup:
      interval: "1h"
      path: "/data/backups"
      compression: true
      max_backups: 5
    security:
      encryption_enabled: false
    logging:
      level: "info"
      format: "json"
