apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiver
  labels:
    app: quiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: quiver
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: quiver
          image: ${REGISTRY}/quiver:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: QUIVER_PORT
              value: "8080"
            - name: QUIVER_DIMENSION
              value: "1536"
            - name: QUIVER_MAX_ELEMENTS
              value: "1000000"
            - name: QUIVER_HNSW_M
              value: "16"
            - name: QUIVER_HNSW_EF_CONSTRUCT
              value: "200"
            - name: QUIVER_HNSW_EF_SEARCH
              value: "100"
            - name: QUIVER_BATCH_SIZE
              value: "100"
            - name: QUIVER_PERSIST_INTERVAL
              value: "5m"
            - name: QUIVER_BACKUP_INTERVAL
              value: "1h"
            - name: QUIVER_MAX_BACKUPS
              value: "5"
            - name: QUIVER_BACKUP_COMPRESSION
              value: "true"
            - name: QUIVER_LOG_LEVEL
              value: "info"
          volumeMounts:
            - name: quiver-data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: quiver-data
          persistentVolumeClaim:
            claimName: quiver-pvc
