apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - configmap.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: quiver
  app.kubernetes.io/instance: quiver
  app.kubernetes.io/part-of: vector-database

namespace: quiver

configMapGenerator:
  - name: quiver-config
    files:
      - quiver.yaml=configmap.yaml

images:
  - name: ${REGISTRY}/quiver
    newTag: ${TAG}
