apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quiver.fullname" . }}-config
  labels:
    {{- include "quiver.labels" . | nindent 4 }}
data:
  quiver.yaml: |
    dimension: {{ .Values.config.dimension }}
    distance: "{{ .Values.config.distance }}"
    max_elements: {{ .Values.config.maxElements }}
    hnsw:
      m: {{ .Values.config.hnsw.m }}
      ef_construction: {{ .Values.config.hnsw.efConstruction }}
      ef_search: {{ .Values.config.hnsw.efSearch }}
    batch_size: {{ .Values.config.batchSize }}
    persistence:
      interval: "{{ .Values.config.persistence.interval }}"
      path: "{{ .Values.config.persistence.path }}"
    backup:
      interval: "{{ .Values.config.backup.interval }}"
      path: "{{ .Values.config.backup.path }}"
      compression: {{ .Values.config.backup.compression }}
      max_backups: {{ .Values.config.backup.maxBackups }}
    security:
      encryption_enabled: {{ .Values.config.security.encryptionEnabled }}
    logging:
      level: "{{ .Values.config.logging.level }}"
      format: "{{ .Values.config.logging.format }}" 