name: Documentation

on:
  push:
    branches: [main]
    paths:
      - "quiver/python/quiver/docs/**"
      - "quiver/python/quiver/mkdocs.yml"
  pull_request:
    branches: [main]
    paths:
      - "quiver/python/quiver/docs/**"
      - "quiver/python/quiver/mkdocs.yml"
  # Allow manual trigger
  workflow_dispatch:

# Skip this workflow
jobs:
  build-docs:
    # This condition will always be false, effectively skipping this job
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-minify-plugin pymdown-extensions
          # Install any additional requirements for docs
          if [ -f quiver/python/quiver/docs/requirements.txt ]; then 
            pip install -r quiver/python/quiver/docs/requirements.txt
          fi

      - name: Build documentation
        run: |
          cd quiver/python/quiver
          mkdocs build --strict

      - name: Check for broken links
        run: |
          cd quiver/python/quiver
          pip install linkchecker
          linkchecker site/ --check-extern

      # Only deploy docs on push to main
      - name: Deploy documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./quiver/python/quiver/site
          full_commit_message: "docs: update documentation site"
